name: Anzo Migration Package Promotion

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  confirm-deployment:
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.confirm.outputs.proceed }}
    steps:
      - name: Confirm Deployment
        id: confirm
        run: |
          if [ "${{ github.event.inputs.proceed }}" != "true" ]; then
            echo "Build wasn't confirmed. Aborting."
            exit 1
          else
            echo "Build confirmed. Proceeding."
            echo "proceed=true" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify-tools:
    runs-on: ubuntu-latest
    needs: confirm-deployment
    if: ${{ needs.confirm-deployment.outputs.proceed == 'true' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key for anzo-dev
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_DEV_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_dev
          chmod 600 ~/.ssh/id_rsa_dev
        env:
          EC2_DEV_SSH_PRIVATE_KEY: ${{ secrets.EC2_DEV_SSH_PRIVATE_KEY }}

      - name: Setup SSH Key for anzo-qa
        run: |
          echo "${{ secrets.EC2_QA_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_qa
          chmod 600 ~/.ssh/id_rsa_qa
        env:
          EC2_QA_SSH_PRIVATE_KEY: ${{ secrets.EC2_QA_SSH_PRIVATE_KEY }}

      - name: Verify Tools on anzo-dev
        env:
          EC2_USER_DEV: ${{ secrets.EC2_USER_DEV }}
          ANZO_DEV_HOST: ${{ secrets.ANZO_DEV_HOST }}
        run: |
          ssh -i ~/.ssh/id_rsa_dev -o StrictHostKeyChecking=no ${EC2_USER_DEV}@${ANZO_DEV_HOST} '
          missing_tools=()
          if ! [ -f /opt/anzo/Client/anzo ]; then
              missing_tools+=("anzo")
          fi
          if ! command -v jq > /dev/null; then
              missing_tools+=("jq")
          fi
          if ! command -v curl > /dev/null; then
              missing_tools+=("curl")
          fi
          if [ ${#missing_tools[@]} -ne 0 ]; then
              echo "Missing tools on anzo-dev: ${missing_tools[@]}"
              exit 1
          fi
          '

      - name: Verify Tools on anzo-qa
        env:
          EC2_USER_QA: ${{ secrets.EC2_USER_QA }}
          ANZO_QA_HOST: ${{ secrets.ANZO_QA_HOST }}
        run: |
          ssh -i ~/.ssh/id_rsa_qa -o StrictHostKeyChecking=no ${EC2_USER_QA}@${ANZO_QA_HOST} '
          missing_tools=()
          if ! [ -f /opt/anzo/Client/anzo ]; then
              missing_tools+=("anzo")
          fi
          if ! command -v jq > /dev/null; then
              missing_tools+=("jq")
          fi
          if ! command -v curl > /dev/null; then
              missing_tools+=("curl")
          fi
          if [ ${#missing_tools[@]} -ne 0 ]; then
              echo "Missing tools on anzo-qa: ${missing_tools[@]}"
              exit 1
          fi
          '

  list-migration-package:
    runs-on: ubuntu-latest
    needs: verify-tools
    if: ${{ needs.verify-tools.result == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Migration Package on anzo-dev
        env:
          SYSADMIN_USER: ${{ secrets.SYSADMIN_USER }}
          SYSADMIN_PASSWORD: ${{ secrets.SYSADMIN_PASSWORD }}
          EC2_USER_DEV: ${{ secrets.EC2_USER_DEV }}
          ANZO_DEV_HOST: ${{ secrets.ANZO_DEV_HOST }}
          MIGRATION_PACKAGE_ID: ${{ secrets.MIGRATION_PACKAGE_ID }}
        run: |
          anzo_dev_response=$(ssh -i ~/.ssh/id_rsa_dev -o StrictHostKeyChecking=no ${EC2_USER_DEV}@${ANZO_DEV_HOST} "
            curl -k -X GET 'https://dev-anzo.dataplatform.rtx.com/api/migration/http://cambridgesemantics.com/MigrationPackage/${MIGRATION_PACKAGE_ID}' \
            -H 'accept: application/json' \
            -u ${SYSADMIN_USER}:${SYSADMIN_PASSWORD} | jq")
          echo "Migration Package Details on anzo-dev: ${anzo_dev_response}"

      - name: List Migration Package on anzo-qa
        env:
          SYSADMIN_USER: ${{ secrets.SYSADMIN_USER }}
          SYSADMIN_PASSWORD: ${{ secrets.SYSADMIN_PASSWORD }}
          EC2_USER_QA: ${{ secrets.EC2_USER_QA }}
          ANZO_QA_HOST: ${{ secrets.ANZO_QA_HOST }}
          MIGRATION_PACKAGE_ID: ${{ secrets.MIGRATION_PACKAGE_ID }}
        run: |
          anzo_qa_response=$(ssh -i ~/.ssh/id_rsa_qa -o StrictHostKeyChecking=no ${EC2_USER_QA}@${ANZO_QA_HOST} "
            curl -k -X GET 'https://dev-anzo.dataplatform.rtx.com/api/migration/http://cambridgesemantics.com/MigrationPackage/${MIGRATION_PACKAGE_ID}' \
            -H 'accept: application/json' \
            -u ${SYSADMIN_USER}:${SYSADMIN_PASSWORD} | jq")
          echo "Migration Package Details on anzo-qa: ${anzo_qa_response}"
